# Generated by Django 4.1.3 on 2022-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.PositiveBigIntegerField(default=1500, max_length=100, verbose_name="Ko'rishlar soni"),
            preserve_default=False,
        ),
    ]
